### ISSUE TITLE
SockAddress.h: No such file or directory

### ISSUE THREAD

**Issue by K2IE** [n7tae/sgs-remote#1]
When compiling on Debian 9.9 (amd64), the following error occurred:

g++ -W -Wall -I/usr/include -std=c++11 -DCFG_DIR=\"/usr/local/etc\" -MMD -MD -c App.cpp -o App.o
In file included from Handler.h:26:0,
                 from App.cpp:29:
UDPReaderWriter.h:32:25: fatal error: SockAddress.h: No such file or directory
 #include "SockAddress.h"
                         ^
compilation terminated.
Makefile:19: recipe for target 'App.o' failed
make: *** [App.o] Error 1

**Comment by w1bsb** [comment]
sgs-remote has not been updated since the changes were made to add IPv6 support to the smart-group-server.  I suggest for the time being, you create a temporary directory, git clone both smart-group-server, and sgs-remote in the temporary directory, and do a git checkout 4dfbd36 in the smart-group-server directory (to run at a detached head state that sgs-remote can build against), then build sgs-remote.  This has been tested on Debian 9, so it should work for you until the sgs-remote program is updated with the new IPv6 support.

sgs-remote builds against smart-group-server, hence the reason for the temporary directory and detached head state of the smart-group-server source. Obviously, you don't want to run your production sgs in detached head.

**Comment by n7tae** [comment]
fixed.
